spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskDB?createDatabaseIfNotExist=true
    username: root
    password: Sohrab@78692
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:    name: task